# Generated by Django 5.1.3 on 2024-11-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_post_content"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
